name: build & test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Clang format
        run: sudo apt-get install clang-format
      - name: Run Clang format check
        run: make fmt

  build:
    runs-on: ubuntu-latest
    container:
      image: vsaglib/vsag:ubuntu
    steps:
      - uses: actions/checkout@v4
      - name: Load Cache
        uses: actions/cache@v4.1.2
        with:
          path: ./build/
          key: build-${{ hashFiles('./CMakeLists.txt') }}-${{ hashFiles('./.circleci/fresh_ci_cache.commit') }}
      - name: Make Asan
        run: make asan
      - name: Save Cache
        uses: actions/cache@v4.1.2
        with:
          path: ./build/
          key: build-${{ hashFiles('./CMakeLists.txt') }}-${{ hashFiles('./.circleci/fresh_ci_cache.commit') }}
      - name: Test
        run: make test_asan