name: DCO Check

on: 
  pull_request:
    branches: [ "main" ]

jobs:
  dco-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate DCO
        uses: tisonkun/actions-dco@v1.1
